/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academiavisual;

import View.TelaInicial;
import Autenticacao.Permissao;
import DAO.AlunoJpaController;
import DAO.TreinadorJpaController;
import DataBase.Aluno;
import DataBase.Treinador;
import com.google.common.base.Charsets;
import com.google.common.hash.Hashing;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author luccas
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxLogin = new javax.swing.JComboBox();
        jPasswordFieldLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("projetoAcademiaVisuall");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Login");
        jLabel1.setName("loginLabel"); // NOI18N

        jButtonFechar.setText("Fechar");
        jButtonFechar.setName("exitButton"); // NOI18N
        jButtonFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFecharMouseClicked(evt);
            }
        });
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonLogin.setText("Login");
        jButtonLogin.setName("loginButton"); // NOI18N
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseClicked(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jTextFieldLogin.setName("usernameField"); // NOI18N
        jTextFieldLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldLoginMouseClicked(evt);
            }
        });
        jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginActionPerformed(evt);
            }
        });

        jLabel2.setText("Senha");
        jLabel2.setName("passwordLabel"); // NOI18N

        jComboBoxLogin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aluno", "Treinador" }));

        jPasswordFieldLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBoxLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(jButtonLogin)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFechar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldLogin))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechar)
                    .addComponent(jButtonLogin)
                    .addComponent(jComboBoxLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFecharMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonFecharMouseClicked

    private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        try {
            permissao = new Permissao();
            if (jComboBoxLogin.getSelectedIndex() == 0) {
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("AcademiaVisualPU");
                AlunoJpaController alunoJpaController = new AlunoJpaController(emf);
                Aluno alunoLogin = (Aluno) alunoJpaController.findLogin(jTextFieldLogin.getText());
                if (alunoLogin != null) {
                    String senha1 = alunoLogin.getSenha();
                    String senha2 = Hashing.sha256().hashString(jPasswordFieldLogin.getText(), Charsets.UTF_8).toString();
                    if (senha1.equals(senha2)) {
                        permissao.setPermissaoUsuario(Permissao.P_ALUNO);
                        ALUNOID = alunoLogin.getId();
                        dispose();
                        JOptionPane.showMessageDialog(null, "Login realizado com sucesso !");
                        new TelaInicial(permissao).setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Senha incorreta!");
                        jPasswordFieldLogin.setText("");
                        jPasswordFieldLogin.grabFocus();
                        contadorAcessoAluno++;
                        if (contadorAcessoAluno == 3) {
                            JOptionPane.showMessageDialog(null, "Quantidade de tentativas excedidas (3)!");
                            System.exit(0);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Login incorreto !");
                    jTextFieldLogin.setText("");
                    jPasswordFieldLogin.setText("");
                    jTextFieldLogin.grabFocus();
                }
            } else {
                if (jComboBoxLogin.getSelectedIndex() == 1) {
                    EntityManagerFactory emf = Persistence.createEntityManagerFactory("AcademiaVisualPU");
                    TreinadorJpaController treinadorJpaController = new TreinadorJpaController(emf);
                    Treinador treinadorLogin = (Treinador) treinadorJpaController.findLogin(jTextFieldLogin.getText());
                    if (treinadorLogin != null) {
                        String senha1 = treinadorLogin.getSenha();
                        String senha2 = Hashing.sha256().hashString(jPasswordFieldLogin.getText(), Charsets.UTF_8).toString();
                        if (senha1.equals(senha2)) {
                            if (treinadorLogin.getAdministrador() == 1) {
                                permissao.setPermissaoUsuario(Permissao.P_ADMINISTRADOR);
                            } else {
                                permissao.setPermissaoUsuario(Permissao.P_TREINADOR);
                            }
                            TREINADORID = treinadorLogin.getId();
                            dispose();
                            JOptionPane.showMessageDialog(null, "Login realizado com sucesso !");
                            new TelaInicial(permissao).setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Senha incorreta!");
                            jPasswordFieldLogin.setText("");
                            jPasswordFieldLogin.grabFocus();
                            contadorAcessoTreinador++;
                            if (contadorAcessoTreinador == 3) {
                                JOptionPane.showMessageDialog(null, "Quantidade de tentativas excedidas (3)!");
                                System.exit(0);
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Login incorreto !");
                        jTextFieldLogin.setText("");
                        jPasswordFieldLogin.setText("");
                        jTextFieldLogin.grabFocus();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseClicked
        /*Botao de Login*/
        /*Index 0 => Aluno;
         Index 1 => Treinador;
         */

        /*
         int currentSelection = jComboBoxLogin.getSelectedIndex();
         permissao = new Permissao();
         switch(currentSelection) {
         case 0:
         permissao.setPermissaoUsuario(Permissao.P_ALUNO);
         break;
         case 1:
         permissao.setPermissaoUsuario(Permissao.P_TREINADOR);
         break;
         }
         dispose();
         new TelaInicial(permissao).setVisible(true);                
         */
    }//GEN-LAST:event_jButtonLoginMouseClicked

    private void jTextFieldLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldLoginMouseClicked
        
    }//GEN-LAST:event_jTextFieldLoginMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jPasswordFieldLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldLoginMouseClicked
        
    }//GEN-LAST:event_jPasswordFieldLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }
    //Para autenticação:
    private Permissao permissao;
    //Contador para tentativas de acesso, no caso tres acessos.
    private int contadorAcessoAluno = 0;
    private int contadorAcessoTreinador = 0;
    //var guardar o id do aluno ou treinador que atualmente esta logado no sistema.
    static public int ALUNOID = 0;
    static public int TREINADORID = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JComboBox jComboBoxLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordFieldLogin;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
