/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.AlunoJpaController;
import DataBase.Aluno;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author afnsoo
 */
public class JInternalFrameCadastroAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameCadastroAluno
     */
    public JInternalFrameCadastroAluno() {
        initComponents();
        jTabbedPaneAluno.setEnabled(true);
        jTabbedPaneAluno.setEnabledAt(0, false);        
        jButtonCancelarAluno.setEnabled(false);
        jButtonConfirmarAluno.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        AcademiaVisualPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AcademiaVisualPU").createEntityManager();
        alunoQuery = java.beans.Beans.isDesignTime() ? null : AcademiaVisualPUEntityManager.createQuery("SELECT a FROM Aluno a");
        alunoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : alunoQuery.getResultList();
        jTabbedPaneAluno = new javax.swing.JTabbedPane();
        jPanelConsultaAluno = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAluno = new javax.swing.JTable();
        jLabelProcurarAluno = new javax.swing.JLabel();
        jTextFieldProcurarAluno = new javax.swing.JTextField();
        jComboBoxProcurarAluno = new javax.swing.JComboBox();
        jButtonProcurarAluno = new javax.swing.JButton();
        jPanelAlterarAluno = new javax.swing.JPanel();
        jLabelNomeAluno = new javax.swing.JLabel();
        jLabelCpfAluno = new javax.swing.JLabel();
        jLabelDataNascimentoAluno = new javax.swing.JLabel();
        jLabelPesoAluno = new javax.swing.JLabel();
        jLabelAlturaAluno = new javax.swing.JLabel();
        jLabelEnderecoAluno = new javax.swing.JLabel();
        jLabelLoginAluno = new javax.swing.JLabel();
        jLabelSenhaAluno = new javax.swing.JLabel();
        jLabelEmailAluno = new javax.swing.JLabel();
        jLabelValidadeAluno = new javax.swing.JLabel();
        jTextFieldNomeAluno = new javax.swing.JTextField();
        jTextFieldPesoAluno = new javax.swing.JTextField();
        jTextFieldAlturaAluno = new javax.swing.JTextField();
        jTextFieldEnderecoAluno = new javax.swing.JTextField();
        jTextFieldLoginAluno = new javax.swing.JTextField();
        jTextFieldEmailAluno = new javax.swing.JTextField();
        jPasswordFieldSenhaAluno = new javax.swing.JPasswordField();
        jLabelIdAluno = new javax.swing.JLabel();
        jTextFieldIdAluno = new javax.swing.JTextField();
        jCheckBoxSenhaAluno = new javax.swing.JCheckBox();
        jFormattedTextFieldDataAluno = new javax.swing.JFormattedTextField();
        jFormattedTextFieldValidadeAluno = new javax.swing.JFormattedTextField();
        jFormattedTextFieldUltimaEntradaAluno = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldCpfAluno = new javax.swing.JFormattedTextField();
        jButtonInserirAluno = new javax.swing.JButton();
        jButtonAlterarAluno = new javax.swing.JButton();
        jButtonExcluirAluno = new javax.swing.JButton();
        jButtonFecharAluno = new javax.swing.JButton();
        jButtonCancelarAluno = new javax.swing.JButton();
        jButtonConfirmarAluno = new javax.swing.JButton();

        setTitle("Cadastro Aluno");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, alunoList, jTableAluno);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${endereco}"));
        columnBinding.setColumnName("Endereco");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataNascimento}"));
        columnBinding.setColumnName("DataNascimento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${altura}"));
        columnBinding.setColumnName("Altura");
        columnBinding.setColumnClass(Float.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${peso}"));
        columnBinding.setColumnName("Peso");
        columnBinding.setColumnClass(Float.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${validade}"));
        columnBinding.setColumnName("Validade");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTableAluno);

        jLabelProcurarAluno.setText("Opção De Busca");

        jTextFieldProcurarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProcurarAlunoActionPerformed(evt);
            }
        });

        jComboBoxProcurarAluno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Id", "Nome", "CPF", "Validade" }));

        jButtonProcurarAluno.setText("Buscar");
        jButtonProcurarAluno.setMaximumSize(new java.awt.Dimension(75, 23));
        jButtonProcurarAluno.setMinimumSize(new java.awt.Dimension(75, 23));
        jButtonProcurarAluno.setPreferredSize(new java.awt.Dimension(75, 23));

        javax.swing.GroupLayout jPanelConsultaAlunoLayout = new javax.swing.GroupLayout(jPanelConsultaAluno);
        jPanelConsultaAluno.setLayout(jPanelConsultaAlunoLayout);
        jPanelConsultaAlunoLayout.setHorizontalGroup(
            jPanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
            .addGroup(jPanelConsultaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProcurarAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxProcurarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldProcurarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonProcurarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConsultaAlunoLayout.setVerticalGroup(
            jPanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaAlunoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProcurarAluno)
                    .addComponent(jTextFieldProcurarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProcurarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProcurarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPaneAluno.addTab("Consulta", jPanelConsultaAluno);

        jLabelNomeAluno.setText("Nome:");

        jLabelCpfAluno.setText("CPF:");

        jLabelDataNascimentoAluno.setText("Data Nascimento:");

        jLabelPesoAluno.setText("Peso:");

        jLabelAlturaAluno.setText("Altura:");

        jLabelEnderecoAluno.setText("Endereco:");

        jLabelLoginAluno.setText("Login:");

        jLabelSenhaAluno.setText("Senha:");

        jLabelEmailAluno.setText("Email:");

        jLabelValidadeAluno.setText("Validade:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), jTextFieldNomeAluno, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.peso}"), jTextFieldPesoAluno, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.altura}"), jTextFieldAlturaAluno, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.endereco}"), jTextFieldEnderecoAluno, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.login}"), jTextFieldLoginAluno, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.email}"), jTextFieldEmailAluno, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.senha}"), jPasswordFieldSenhaAluno, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabelIdAluno.setText("ID:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.id}"), jTextFieldIdAluno, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jCheckBoxSenhaAluno.setText("Trocar Senha P.A.");

        jFormattedTextFieldDataAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/M/d"))));
        jFormattedTextFieldDataAluno.setText("yyyy/M/d");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dataNascimento}"), jFormattedTextFieldDataAluno, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jFormattedTextFieldDataAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextFieldDataAlunoMouseClicked(evt);
            }
        });

        jFormattedTextFieldValidadeAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/M/d"))));
        jFormattedTextFieldValidadeAluno.setText("yyyy/M/d");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.validade}"), jFormattedTextFieldValidadeAluno, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jFormattedTextFieldValidadeAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextFieldValidadeAlunoMouseClicked(evt);
            }
        });

        jFormattedTextFieldUltimaEntradaAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/M/d"))));
        jFormattedTextFieldUltimaEntradaAluno.setText("yyyy/M/d");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ultimaEntrada}"), jFormattedTextFieldUltimaEntradaAluno, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jFormattedTextFieldUltimaEntradaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextFieldUltimaEntradaAlunoMouseClicked(evt);
            }
        });

        jLabel1.setText("Ultima Entrada:");

        try {
            jFormattedTextFieldCpfAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableAluno, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cpf}"), jFormattedTextFieldCpfAluno, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanelAlterarAlunoLayout = new javax.swing.GroupLayout(jPanelAlterarAluno);
        jPanelAlterarAluno.setLayout(jPanelAlterarAlunoLayout);
        jPanelAlterarAlunoLayout.setHorizontalGroup(
            jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlterarAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEnderecoAluno)
                    .addComponent(jLabelCpfAluno)
                    .addComponent(jLabelNomeAluno)
                    .addComponent(jLabelDataNascimentoAluno)
                    .addComponent(jLabelPesoAluno)
                    .addComponent(jLabelLoginAluno)
                    .addComponent(jLabelEmailAluno)
                    .addComponent(jLabelValidadeAluno)
                    .addComponent(jLabelIdAluno)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jFormattedTextFieldUltimaEntradaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNomeAluno)
                        .addComponent(jTextFieldEmailAluno, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlterarAlunoLayout.createSequentialGroup()
                            .addComponent(jTextFieldPesoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAlturaAluno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldAlturaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelAlterarAlunoLayout.createSequentialGroup()
                            .addComponent(jTextFieldLoginAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelSenhaAluno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPasswordFieldSenhaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jFormattedTextFieldDataAluno)
                        .addComponent(jFormattedTextFieldValidadeAluno)
                        .addComponent(jFormattedTextFieldCpfAluno))
                    .addComponent(jTextFieldEnderecoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxSenhaAluno)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanelAlterarAlunoLayout.setVerticalGroup(
            jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlterarAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdAluno)
                    .addComponent(jTextFieldIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeAluno)
                    .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpfAluno)
                    .addComponent(jFormattedTextFieldCpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataNascimentoAluno)
                    .addComponent(jFormattedTextFieldDataAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesoAluno)
                    .addComponent(jTextFieldPesoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAlturaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlturaAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnderecoAluno)
                    .addComponent(jTextFieldEnderecoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoginAluno)
                    .addComponent(jTextFieldLoginAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenhaAluno)
                    .addComponent(jPasswordFieldSenhaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxSenhaAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmailAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmailAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValidadeAluno)
                    .addComponent(jFormattedTextFieldValidadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlterarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldUltimaEntradaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPaneAluno.addTab("Alterar", jPanelAlterarAluno);

        jButtonInserirAluno.setText("Inserir");
        jButtonInserirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirAlunoActionPerformed(evt);
            }
        });

        jButtonAlterarAluno.setText("Alterar");
        jButtonAlterarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarAlunoActionPerformed(evt);
            }
        });

        jButtonExcluirAluno.setText("Excluir");
        jButtonExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirAlunoActionPerformed(evt);
            }
        });

        jButtonFecharAluno.setText("Fechar");
        jButtonFecharAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharAlunoActionPerformed(evt);
            }
        });

        jButtonCancelarAluno.setText("Cancelar");
        jButtonCancelarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAlunoActionPerformed(evt);
            }
        });

        jButtonConfirmarAluno.setText("Confirmar");
        jButtonConfirmarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAluno)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInserirAluno)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterarAluno)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluirAluno)
                .addGap(18, 18, 18)
                .addComponent(jButtonConfirmarAluno)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelarAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFecharAluno)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInserirAluno)
                    .addComponent(jButtonAlterarAluno)
                    .addComponent(jButtonExcluirAluno)
                    .addComponent(jButtonFecharAluno)
                    .addComponent(jButtonCancelarAluno)
                    .addComponent(jButtonConfirmarAluno))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //controle botoes CRUD.
    private int ANTERIOR = 0;
    private final int INSERIR = 1;
    private final int ALTERAR = 2;
    private final int EXCLUIR = 3;
    private final int CONFIRMAR = 4;
    private final int CANCELAR = 5;
    
    //controle alternancia entre tela consulta e alterar.
    private final int telaConsultar = 1;
    private final int telaAlterar = 2;
    
    private void limparCamposCadastroAluno(){
        jTextFieldAlturaAluno.setText("");
        jTextFieldEmailAluno.setText("");
        jTextFieldEnderecoAluno.setText("");
        jTextFieldIdAluno.setText("");
        jTextFieldLoginAluno.setText("");
        jTextFieldNomeAluno.setText("");
        jTextFieldPesoAluno.setText("");
        jTextFieldProcurarAluno.setText("");
        jFormattedTextFieldCpfAluno.setText("");
        jFormattedTextFieldDataAluno.setText("");
        jFormattedTextFieldUltimaEntradaAluno.setText("");
        jFormattedTextFieldValidadeAluno.setText("");
        jCheckBoxSenhaAluno.setSelected(false);
    }
    
    private void controleTela(int opTela){
        switch (opTela){
            case telaConsultar: {    
                jTabbedPaneAluno.setEnabled(true);
                jTabbedPaneAluno.setEnabledAt(0, true);
                jTabbedPaneAluno.setSelectedIndex(0);
                jTabbedPaneAluno.setEnabledAt(1, false);
                jButtonAlterarAluno.setEnabled(true);
                jButtonInserirAluno.setEnabled(true);
                jButtonExcluirAluno.setEnabled(true);
                jButtonFecharAluno.setEnabled(true);
                jButtonConfirmarAluno.setEnabled(false);
                jButtonCancelarAluno.setEnabled(false);
            }
            case telaAlterar: {    
                jTabbedPaneAluno.setEnabled(true);
                jTabbedPaneAluno.setEnabledAt(1, true);
                jTabbedPaneAluno.setSelectedIndex(1);
                jTabbedPaneAluno.setEnabledAt(0, false);
                jButtonAlterarAluno.setEnabled(false);
                jButtonInserirAluno.setEnabled(false);
                jButtonExcluirAluno.setEnabled(false);
                jButtonFecharAluno.setEnabled(false);
                jButtonConfirmarAluno.setEnabled(true);
                jButtonCancelarAluno.setEnabled(true);
            }
        }
    }
    
    private int verificarCamposAluno(){
        int erros = 0;
        try {
            if (ANTERIOR == INSERIR || ANTERIOR == ALTERAR) {                
                Pattern p = Pattern.compile("^[\\w-]+(\\.[\\w-]+)*@([\\w-]+\\.)+[a-zA-Z]{2,7}$");
                Matcher m = p.matcher(jTextFieldEmailAluno.getText());
                boolean emailValido = m.find();
                if (!(jTextFieldNomeAluno.getText().length() > 40 || "".equals(jTextFieldNomeAluno.getText()))) {
                    alunoList.get(alunoList.size() - 1).setNome(jTextFieldNomeAluno.getText());
                    if (!(jTextFieldEnderecoAluno.getText().length() > 40 || ("".equals(jTextFieldEnderecoAluno.getText())))) {
                        alunoList.get(alunoList.size() - 1).setEndereco(jTextFieldEnderecoAluno.getText());                                                    
                                if (!(jFormattedTextFieldCpfAluno.getText().replaceAll("[^0123456789]", "").length() != 11)) {
                                    alunoList.get(alunoList.size() - 1).setCpf(jFormattedTextFieldCpfAluno.getText());
                                    if (!(jTextFieldEmailAluno.getText().length() > 40 || ("".equals(jTextFieldEmailAluno.getText()))) && emailValido) {
                                        alunoList.get(alunoList.size() - 1).setEmail(jTextFieldEmailAluno.getText());
                                        if (!(jTextFieldLoginAluno.getText().length() > 10 || ("".equals(jTextFieldLoginAluno.getText())))) {
                                            try {
                                                EntityManagerFactory emf = Persistence.createEntityManagerFactory("AcademiaVisualPU");
                                                AlunoJpaController alunoJpaController = new AlunoJpaController(emf);
                                                Aluno alunoAux = (Aluno) alunoJpaController.findLogin(jTextFieldLoginAluno.getText());                                                
                                                    if (alunoAux != null) {
                                                        erros++;
                                                        jTextFieldLoginAluno.setText("");
                                                        jTextFieldLoginAluno.grabFocus();
                                                        JOptionPane.showMessageDialog(null, "Este login já está sendo utilizado.");
                                                    } else {
                                                        alunoList.get(alunoList.size() - 1).setLogin(jTextFieldLoginAluno.getText());
                                                    }                                                                                                
                                            } catch (Exception e) {
                                                JOptionPane.showMessageDialog(null, e);
                                            }
                                            if ((jPasswordFieldSenhaAluno.getText().length() >= 6 && jPasswordFieldSenhaAluno.getText().length() <= 15)) {
                                                //precisa criptografar a senha antes de guardar no banco.
                                                //alunoList.get(alunoList.size() - 1).setSenha(Hashing.sha256().hashString(jPasswordFieldSenhaAluno.getText(), Charsets.UTF_8).toString());
                                                alunoList.get(alunoList.size() - 1).setSenha(jPasswordFieldSenhaAluno.getText());                                                                                                                                                    
                                            } else {
                                                if (!(ANTERIOR == ALTERAR && !"".equals(jPasswordFieldSenhaAluno.getText()))) {
                                                    if ((ANTERIOR == INSERIR) || (ANTERIOR == ALTERAR && (jPasswordFieldSenhaAluno.getText().length() < 6 || jPasswordFieldSenhaAluno.getText().length() > 15) && !"".equals(jPasswordFieldSenhaAluno.getText())) || (ANTERIOR == ALTERAR)) {
                                                        erros++;
                                                        JOptionPane.showMessageDialog(null, "O campo senha deve ter entre 6 e 15 caracteres não pode estar em branco");
                                                        jPasswordFieldSenhaAluno.setText("");                                                        
                                                        jPasswordFieldSenhaAluno.grabFocus();
                                                    }
                                                }
                                            }
                                        } else {
                                            erros++;
                                            JOptionPane.showMessageDialog(null, "O campo login deve ter menos de 10 caracteres e não pode estar em branco");
                                            jTextFieldLoginAluno.setText("");
                                            jTextFieldLoginAluno.grabFocus();
                                        }

                                    } else {
                                        erros++;
                                        JOptionPane.showMessageDialog(null, "O campo email deve ter menos de 40 caracteres, não pode estar em branco e precisa ser válido");
                                        jTextFieldEmailAluno.setText("");
                                        jTextFieldEmailAluno.grabFocus();
                                    }
                                } else {
                                    erros++;
                                    JOptionPane.showMessageDialog(null, "O campo cpf deve ter 14 caracteres no formato 123.123.123-12 e não pode estar em branco");
                                    jFormattedTextFieldCpfAluno.grabFocus();
                                }                                                    
                    } else {
                        erros++;
                        JOptionPane.showMessageDialog(null, "O campo endereço deve ter menos de 40 caracteres e não pode estar em branco");
                        jTextFieldEnderecoAluno.setText("");
                        jTextFieldEnderecoAluno.grabFocus();
                    }
                } else {
                    erros++;
                    JOptionPane.showMessageDialog(null, "O campo nome deve ter menos de 40 caracteres e não pode estar em branco");
                    jTextFieldNomeAluno.setText("");
                    jTextFieldNomeAluno.grabFocus();
                }                                
        } 
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  
        return erros;
    }
    
    private void controle(int op){
        try {
            switch(op){
                case INSERIR: {
                    this.ANTERIOR = INSERIR;
                    limparCamposCadastroAluno();
                    controleTela(telaAlterar);
                    alunoList.add(new Aluno());
                    jTableAluno.updateUI();
                    jTableAluno.repaint();
                    jTableAluno.setRowSelectionInterval(jTableAluno.getRowCount() - 1, jTableAluno.getRowCount() - 1);
                    break;                   
                }
                case ALTERAR: {                    
                    if (!alunoList.isEmpty() && jTableAluno.getSelectedRow() != -1) {
                        this.ANTERIOR = ALTERAR;                        
                        controleTela(telaAlterar);                        
                        Aluno a = alunoList.get(jTableAluno.getSelectedRow());
                        alunoList.add(a);
                        jTableAluno.updateUI();
                        jTableAluno.repaint();
                        jTableAluno.setRowSelectionInterval(jTableAluno.getRowCount() - 1, jTableAluno.getRowCount() - 1);
                    } else {
                        JOptionPane.showMessageDialog(null, "Selecione um aluno !");
                    }
                    break;
                }
                case EXCLUIR: {
                    if (!alunoList.isEmpty() && jTableAluno.getSelectedRow() != -1) {
                    this.ANTERIOR = EXCLUIR;
                    int option = JOptionPane.showConfirmDialog(this, "Verifique com atenção os dados que deseja excluir!\n"
                            + "Clique em sim se esse for mesmo o aluno que deseja excluir.\n"
                            + "Clique em cancelar para voltar.");
                    if (option == JOptionPane.YES_OPTION) {
                        try {   
                            /*
                                EXCLUIR O USUARIO DE TODOS AS TABELAS QUE UTILIZAM O MESMO !
                            */        
                            alunoList.get(jTableAluno.getSelectedRow()).excluir();
                            alunoList.remove(jTableAluno.getSelectedRow());
                            jTableAluno.updateUI();
                            jTableAluno.repaint();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Exclusão cancelada !");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Selecione um aluno !");
                }
                break;
                }
                case CONFIRMAR: {
                    switch (ANTERIOR) {
                        case INSERIR: {
                            alunoList.get(alunoList.size() - 1).incluir();
                            jTableAluno.updateUI();
                            jTableAluno.repaint();                    
                            controleTela(telaConsultar);
                            jTableAluno.setRowSelectionInterval(0, 0);
                            break;
                        }
                        case ALTERAR: {                            
                            alunoList.get(alunoList.size() - 1).alterar();                            
                            jTableAluno.updateUI();
                            jTableAluno.repaint();                    
                            controleTela(telaConsultar);                                                        
                            jTableAluno.setRowSelectionInterval(0, 0);
                            break;
                        }                       
                    }
                }
                case CANCELAR: {
                    alunoList.remove(alunoList.size() - 1);
                    jTableAluno.updateUI();
                    jTableAluno.repaint();                    
                    controleTela(telaConsultar);
                    jTableAluno.setRowSelectionInterval(0, 0);
                }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public static final String DateFormat = "yyyy/M/d";

    public static String diaAtual(){
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat format = new SimpleDateFormat(DateFormat);
        return format.format(cal.getTime());
    }
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // fazer verificação de administrador para liberar os botoes de adicionar, alterar e excluir.
        //jFormattedTextFieldUltimaEntradaAluno.setText(diaAtual());
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButtonFecharAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharAlunoActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharAlunoActionPerformed

    private void jButtonInserirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirAlunoActionPerformed
        controle(INSERIR);
    }//GEN-LAST:event_jButtonInserirAlunoActionPerformed

    private void jTextFieldProcurarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProcurarAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProcurarAlunoActionPerformed

    private void jButtonCancelarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAlunoActionPerformed
        controle(CANCELAR);               
    }//GEN-LAST:event_jButtonCancelarAlunoActionPerformed

    private void jButtonConfirmarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarAlunoActionPerformed
        if(verificarCamposAluno() == 0){
            controle(CONFIRMAR);
        }
    }//GEN-LAST:event_jButtonConfirmarAlunoActionPerformed

    private void jButtonAlterarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarAlunoActionPerformed
        controle(ALTERAR);
    }//GEN-LAST:event_jButtonAlterarAlunoActionPerformed

    private void jButtonExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirAlunoActionPerformed
        controle(EXCLUIR);
    }//GEN-LAST:event_jButtonExcluirAlunoActionPerformed

    private void jFormattedTextFieldDataAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataAlunoMouseClicked
        jFormattedTextFieldDataAluno.setText("");
    }//GEN-LAST:event_jFormattedTextFieldDataAlunoMouseClicked

    private void jFormattedTextFieldValidadeAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextFieldValidadeAlunoMouseClicked
        jFormattedTextFieldValidadeAluno.setText("");
    }//GEN-LAST:event_jFormattedTextFieldValidadeAlunoMouseClicked

    private void jFormattedTextFieldUltimaEntradaAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextFieldUltimaEntradaAlunoMouseClicked
        jFormattedTextFieldUltimaEntradaAluno.setText("");
    }//GEN-LAST:event_jFormattedTextFieldUltimaEntradaAlunoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AcademiaVisualPUEntityManager;
    private java.util.List<DataBase.Aluno> alunoList;
    private javax.persistence.Query alunoQuery;
    private javax.swing.JButton jButtonAlterarAluno;
    private javax.swing.JButton jButtonCancelarAluno;
    private javax.swing.JButton jButtonConfirmarAluno;
    private javax.swing.JButton jButtonExcluirAluno;
    private javax.swing.JButton jButtonFecharAluno;
    private javax.swing.JButton jButtonInserirAluno;
    private javax.swing.JButton jButtonProcurarAluno;
    private javax.swing.JCheckBox jCheckBoxSenhaAluno;
    private javax.swing.JComboBox jComboBoxProcurarAluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfAluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataAluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldUltimaEntradaAluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldValidadeAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAlturaAluno;
    private javax.swing.JLabel jLabelCpfAluno;
    private javax.swing.JLabel jLabelDataNascimentoAluno;
    private javax.swing.JLabel jLabelEmailAluno;
    private javax.swing.JLabel jLabelEnderecoAluno;
    private javax.swing.JLabel jLabelIdAluno;
    private javax.swing.JLabel jLabelLoginAluno;
    private javax.swing.JLabel jLabelNomeAluno;
    private javax.swing.JLabel jLabelPesoAluno;
    private javax.swing.JLabel jLabelProcurarAluno;
    private javax.swing.JLabel jLabelSenhaAluno;
    private javax.swing.JLabel jLabelValidadeAluno;
    private javax.swing.JPanel jPanelAlterarAluno;
    private javax.swing.JPanel jPanelConsultaAluno;
    private javax.swing.JPasswordField jPasswordFieldSenhaAluno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneAluno;
    private javax.swing.JTable jTableAluno;
    private javax.swing.JTextField jTextFieldAlturaAluno;
    private javax.swing.JTextField jTextFieldEmailAluno;
    private javax.swing.JTextField jTextFieldEnderecoAluno;
    private javax.swing.JTextField jTextFieldIdAluno;
    private javax.swing.JTextField jTextFieldLoginAluno;
    private javax.swing.JTextField jTextFieldNomeAluno;
    private javax.swing.JTextField jTextFieldPesoAluno;
    private javax.swing.JTextField jTextFieldProcurarAluno;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
