/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DataBase.Evolucaoaluno;

/**
 *
 * @author Luccas
 */
public class JInternalFrameAvaliacaoAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameAvaliacaoAluno
     */
    public JInternalFrameAvaliacaoAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        AcademiaVisualPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AcademiaVisualPU").createEntityManager();
        evolucaoalunoQuery = java.beans.Beans.isDesignTime() ? null : AcademiaVisualPUEntityManager.createQuery("SELECT e FROM Evolucaoaluno e");
        evolucaoalunoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : evolucaoalunoQuery.getResultList();
        jTabbedPaneEvolucaoAluno = new javax.swing.JTabbedPane();
        jPanelConsultaEvolucaoAluno = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEvolucaoAluno = new javax.swing.JTable();
        jPanelAlterarEvolucaoAluno = new javax.swing.JPanel();
        jLabelAlunoID = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextFieldPorcentagemMassaMagra = new javax.swing.JTextField();
        jLabelPeso = new javax.swing.JLabel();
        jLabelPercentualGordura = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldDataMedicao = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonEscolhaEvolucaoAluno = new javax.swing.JButton();
        jButtonInserirEvolucaoAluno = new javax.swing.JButton();
        jButtonExcluirEvolucaoAluno = new javax.swing.JButton();
        jButtonFecharEvolucaoAluno = new javax.swing.JButton();
        jButtonCancelarEvolucaoAluno = new javax.swing.JButton();
        jButtonConfirmarEvolucaoAluno = new javax.swing.JButton();

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, evolucaoalunoList, jTableEvolucaoAluno);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${alunoId}"));
        columnBinding.setColumnName("Aluno Id");
        columnBinding.setColumnClass(DataBase.Aluno.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${peso}"));
        columnBinding.setColumnName("Peso");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataMedicao}"));
        columnBinding.setColumnName("Data Medicao");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${percMassaMagra}"));
        columnBinding.setColumnName("Perc Massa Magra");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${percGordura}"));
        columnBinding.setColumnName("Perc Gordura");
        columnBinding.setColumnClass(Float.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTableEvolucaoAluno);

        javax.swing.GroupLayout jPanelConsultaEvolucaoAlunoLayout = new javax.swing.GroupLayout(jPanelConsultaEvolucaoAluno);
        jPanelConsultaEvolucaoAluno.setLayout(jPanelConsultaEvolucaoAlunoLayout);
        jPanelConsultaEvolucaoAlunoLayout.setHorizontalGroup(
            jPanelConsultaEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        jPanelConsultaEvolucaoAlunoLayout.setVerticalGroup(
            jPanelConsultaEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jTabbedPaneEvolucaoAluno.addTab("Consulta", jPanelConsultaEvolucaoAluno);

        jLabelAlunoID.setText("Aluno");

        jLabelPeso.setText("Peso");

        jLabelPercentualGordura.setText("Percentual de Gordura");

        jLabel5.setText("% Massa Magra");

        jFormattedTextFieldDataMedicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/M/dd"))));

        jLabel7.setText("Data Medição");

        jButtonEscolhaEvolucaoAluno.setText("...");
        jButtonEscolhaEvolucaoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscolhaEvolucaoAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlterarEvolucaoAlunoLayout = new javax.swing.GroupLayout(jPanelAlterarEvolucaoAluno);
        jPanelAlterarEvolucaoAluno.setLayout(jPanelAlterarEvolucaoAlunoLayout);
        jPanelAlterarEvolucaoAlunoLayout.setHorizontalGroup(
            jPanelAlterarEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlterarEvolucaoAlunoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanelAlterarEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlterarEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelPercentualGordura)
                        .addComponent(jLabelAlunoID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelPeso, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlterarEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextFieldPorcentagemMassaMagra)
                    .addComponent(jFormattedTextFieldDataMedicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEscolhaEvolucaoAluno)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanelAlterarEvolucaoAlunoLayout.setVerticalGroup(
            jPanelAlterarEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlterarEvolucaoAlunoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelAlterarEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlunoID)
                    .addComponent(jButtonEscolhaEvolucaoAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlterarEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlterarEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPercentualGordura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlterarEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPorcentagemMassaMagra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlterarEvolucaoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDataMedicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTabbedPaneEvolucaoAluno.addTab("Alterar", jPanelAlterarEvolucaoAluno);

        jButtonInserirEvolucaoAluno.setText("Inserir");
        jButtonInserirEvolucaoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirEvolucaoAlunoActionPerformed(evt);
            }
        });

        jButtonExcluirEvolucaoAluno.setText("Excluir");
        jButtonExcluirEvolucaoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEvolucaoAlunoActionPerformed(evt);
            }
        });

        jButtonFecharEvolucaoAluno.setText("Fechar");
        jButtonFecharEvolucaoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharEvolucaoAlunoActionPerformed(evt);
            }
        });

        jButtonCancelarEvolucaoAluno.setText("Cancelar");
        jButtonCancelarEvolucaoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarEvolucaoAlunoActionPerformed(evt);
            }
        });

        jButtonConfirmarEvolucaoAluno.setText("Confirmar");
        jButtonConfirmarEvolucaoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarEvolucaoAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneEvolucaoAluno)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInserirEvolucaoAluno)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluirEvolucaoAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConfirmarEvolucaoAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelarEvolucaoAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFecharEvolucaoAluno)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneEvolucaoAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInserirEvolucaoAluno)
                    .addComponent(jButtonExcluirEvolucaoAluno)
                    .addComponent(jButtonFecharEvolucaoAluno)
                    .addComponent(jButtonCancelarEvolucaoAluno)
                    .addComponent(jButtonConfirmarEvolucaoAluno))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirEvolucaoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirEvolucaoAlunoActionPerformed
        flagAnterior = INSERIR;
        
        abaAlterar();
    }//GEN-LAST:event_jButtonInserirEvolucaoAlunoActionPerformed

    private void jButtonExcluirEvolucaoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEvolucaoAlunoActionPerformed
       
    }//GEN-LAST:event_jButtonExcluirEvolucaoAlunoActionPerformed

    private void jButtonFecharEvolucaoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharEvolucaoAlunoActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharEvolucaoAlunoActionPerformed

    private void jButtonCancelarEvolucaoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarEvolucaoAlunoActionPerformed
        abaConsulta();
    }//GEN-LAST:event_jButtonCancelarEvolucaoAlunoActionPerformed

    private void jButtonConfirmarEvolucaoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarEvolucaoAlunoActionPerformed
       

    }//GEN-LAST:event_jButtonConfirmarEvolucaoAlunoActionPerformed

    private void jButtonEscolhaEvolucaoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscolhaEvolucaoAlunoActionPerformed
        JDialogEscolherAluno alunoE = new JDialogEscolherAluno(null, closable);
        alunoE.setModal(true);
        alunoE.setVisible(true);
        if (alunoE.SELECIONADO) {
            //inserirAluno = alunoE.getAluno();
            //jTextFieldAlunoTreino.setText(alunoE.getAluno().getNome());
        }
        alunoE.dispose();
    }//GEN-LAST:event_jButtonEscolhaEvolucaoAlunoActionPerformed
/**
     * Entra na Aba de Consulta
     */
    private void abaConsulta() {
        //jTabbedPaneAdicionarEvolucaoAluno.setSelectedIndex(0);
        //jTabbedPaneAdicionarEvolucaoAluno.setEnabledAt(0, true);
        //jTabbedPaneAdicionarEvolucaoAluno.setEnabledAt(1, false);
        jButtonConfirmarEvolucaoAluno.setEnabled(false);
        jButtonCancelarEvolucaoAluno.setEnabled(false);
        jButtonInserirEvolucaoAluno.setEnabled(true);
        //jButtonAlterarEvolucaoAluno.setEnabled(true);
        jButtonExcluirEvolucaoAluno.setEnabled(true);
    }

    /**
     * Entra na Aba de Alterar
     */
    private void abaAlterar() {
        //jTabbedPaneAdicionarEvolucaoAluno.setSelectedIndex(1);
        //jTabbedPaneAdicionarEvolucaoAluno.setEnabledAt(1, true);
        //jTabbedPaneAdicionarEvolucaoAluno.setEnabledAt(0, false);
        jButtonInserirEvolucaoAluno.setEnabled(false);
        //jButtonAlterarEvolucaoAluno.setEnabled(false);
        jButtonExcluirEvolucaoAluno.setEnabled(false);
        jButtonConfirmarEvolucaoAluno.setEnabled(true);
        jButtonCancelarEvolucaoAluno.setEnabled(true);

    }
    private int flagAnterior; //Define qual botão foi clicado
    
    private Evolucaoaluno evolucaoAluno; //Endereça objetos criados

    //Flags para identificar que botão foi clicado anteriormente.
    private final int INSERIR = 1;
    private final int ALTERAR = 2;
    
    private Evolucaoaluno evolucaoAlunoAlterar;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AcademiaVisualPUEntityManager;
    private java.util.List<DataBase.Evolucaoaluno> evolucaoalunoList;
    private javax.persistence.Query evolucaoalunoQuery;
    private javax.swing.JButton jButtonCancelarEvolucaoAluno;
    private javax.swing.JButton jButtonConfirmarEvolucaoAluno;
    private javax.swing.JButton jButtonEscolhaEvolucaoAluno;
    private javax.swing.JButton jButtonExcluirEvolucaoAluno;
    private javax.swing.JButton jButtonFecharEvolucaoAluno;
    private javax.swing.JButton jButtonInserirEvolucaoAluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataMedicao;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAlunoID;
    private javax.swing.JLabel jLabelPercentualGordura;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JPanel jPanelAlterarEvolucaoAluno;
    private javax.swing.JPanel jPanelConsultaEvolucaoAluno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneEvolucaoAluno;
    private javax.swing.JTable jTableEvolucaoAluno;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldPorcentagemMassaMagra;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
